
# Docker Compose 配置文件 - 生产环境部署
# 使用 DockerHub 上的预构建镜像进行部署

services:
  server:
    image: mufeng888/gomailapi2-server:latest  # 使用 DockerHub 上的镜像
    container_name: gomailapi2-server
    restart: unless-stopped  # 容器重启策略
    ports:
      - "8080:8080"   # HTTP 端口
      - "50051:50051" # gRPC 端口
    volumes:
      - ./config.yaml:/config.yaml:ro # 挂载配置文件，只读
    environment:
      - GOMAILAPI_WEBHOOK_BASE_URL=https://372151.xyz
      - GOMAILAPI_ENV=production