# 生产环境 Docker Compose 配置
# 使用预构建的镜像，适用于服务器部署

services:
  server:
    image: mufeng888/gomailapi2-server:latest # 使用 DockerHub 镜像
    restart: always # 自动重启
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - ./config.yaml:/config.yaml:ro # 挂载配置文件，只读
    environment:
      - GOMAILAPI_WEBHOOK_BASE_URL=https://graph.mufengapp.cn
      - GOMAILAPI_ENV=production
