server:
  host: "localhost"
  port: 8080
  grpc_port: 50051

# 缓存配置
cache:
  # 缓存类型: "local", "redis", "multilevel"
  type: "local"
  # 本地缓存配置
  local:
    size: 1000 # 本地缓存容量 (约占用 ~236KB)
    # l1_expiration: "50m" # L1 缓存过期时间
  # Redis 缓存配置
  redis:
    host: "localhost"
    port: "6379"
    password: ""
    db: 0

log:
  level: "debug"
